update_test: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

access_test: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

init_test: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

tcp-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

udp-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

ntp: FORCE
	tinygo flash -target wioterminal $(ARGS) tinygo.org/x/drivers/examples/rtl8720dn/ntpclient

mqttpub-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

mqttsub-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

http-client-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

http-server-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

https-client-tinygo: FORCE
	tinygo flash -target wioterminal $(ARGS) ./$@

FORCE:
